quarkus:
  datasource:
    devservices:
      enabled: true
      image-name: postgres:16
    jdbc:
      url:

  hibernate-orm:
    database:
      generation: drop-and-create

  flyway:
    migrate-at-start: false
