package es.pausegarra.russian_cheatsheet.context.words.domain.enums;

public enum WordType {

  NOUN, PRONOUN_NOUN, PRONOUN_ADJECTIVE, VERB, ADJECTIVE, ADVERB, NUMERAL_CARDINAL, NUMERAL_ADJECTIVE, ORDINAL, PREPOSITION, CONJUNCTION,
  PARTICLE, INTERJECTION,
  GERUND, PARTICIPLE, PREFIX,
  SUFFIX, ROOT, LETTER, SENTENCE, OTHER, SHORT_ADJECTIVE, COMPARATIVE, PREDICATIVE

}
